version: '3'

services:
  bot:
    build: .
    environment:
      - MM_TOKEN=nujq3dbhr78z8c1r49a4c1bt1r
      - MM_URL=http://mattermost:8065
      - TARANTOOL_ADDR=tarantool:3301
    ports:
      - "5000:5000"  # <-- проброс для HTTP-сервера slash-команды
    depends_on:
      - tarantool
      - mattermost
    restart: unless-stopped

  tarantool:
    image: tarantool/tarantool:2
    ports:
      - "3301:3301"
    volumes:
      - ./init.lua:/opt/tarantool/init.lua
    command: tarantool /opt/tarantool/init.lua
    restart: unless-stopped

  mattermost:
    image: mattermost/mattermost-team-edition
    ports:
      - "8065:8065"
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@postgres:5432/mattermost?sslmode=disable
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - bot

volumes:
  postgres_data:

